const STORAGE_PRODUCTS='bella-products',STORAGE_CART='bella-ginastica-cart',STORAGE_ORDERS='bella-orders';
const seedProducts=[{id:1,name:'Top Íris',fabric:'Suplex poliamida',price:69.9,category:'tops',tag:'mais vendido',color:'#f5a58c'},{id:2,name:'Top Move',fabric:'Wonder',price:74.9,category:'tops',tag:'novo',color:'#c9e66a'},{id:3,name:'Cropped Pulse',fabric:'Trilobal',price:79.9,category:'tops',tag:'',color:'#d6b7c9'},{id:4,name:'Legging Essential',fabric:'Suplex poliamida',price:89.9,category:'calcas',tag:'',color:'#b9c8d3'},{id:5,name:'Calça Aura',fabric:'Cirrê',price:99.9,category:'calcas',tag:'novo',color:'#f0d299'},{id:6,name:'Legging Flow',fabric:'Wonder',price:94.9,category:'calcas',tag:'',color:'#aebea8'}];
if(!localStorage.getItem(STORAGE_PRODUCTS))localStorage.setItem(STORAGE_PRODUCTS,JSON.stringify(seedProducts));
const getProducts=()=>JSON.parse(localStorage.getItem(STORAGE_PRODUCTS)||'[]'),money=value=>Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),$=selector=>document.querySelector(selector);let cart=JSON.parse(localStorage.getItem(STORAGE_CART)||'[]');
const saveCart=()=>localStorage.setItem(STORAGE_CART,JSON.stringify(cart)),getProduct=id=>getProducts().find(product=>String(product.id)===String(id));
function subtotal(){return cart.reduce((sum,item)=>{const product=getProduct(item.id);return product?sum+Number(product.price)*item.qty:sum},0)}function isPix(){return $('input[name="pay"]:checked')?.value==='PIX'}function total(){return subtotal()*(isPix()?.95:1)}
function render(items){$('#product-grid').innerHTML=items.map(product=>`<article class="product"><div class="product-image" data-type="${product.category==='tops'?'TOP':product.category==='calcas'?'CALÇA':'CONJUNTO'}" style="--product-color:${product.color||'#c9e66a'}">${product.photo?`<img class="product-photo" src="${product.photo}" alt="${product.name}">`:''}${product.tag?`<span class="tag">${product.tag}</span>`:''}<button class="add" aria-label="Adicionar ${product.name}" data-id="${product.id}">+</button></div><div class="product-info"><div><h3>${product.name}</h3><p>${product.fabric||product.description||'Moda fitness'}</p></div><b>${money(product.price)}</b></div></article>`).join('')||'<p class="empty-catalogue">Nenhuma peça nesta coleção ainda.</p>'}
function setFilter(filter){const labels={todos:['Acabou de chegar','Novidades <i>Bella</i>'],tops:['Coleção Bella','Tops <i>para treinar</i>'],calcas:['Coleção Bella','Calças <i>para se mover</i>'],conjuntos:['Coleção Bella','Conjuntos <i>para combinar</i>']}[filter];$('#catalogue-label').textContent=labels[0];$('#catalogue-title').innerHTML=labels[1];document.querySelectorAll('.catalogue-tabs [data-filter]').forEach(button=>button.classList.toggle('active',button.dataset.filter===filter));const products=getProducts();render(filter==='todos'?products:products.filter(product=>product.category===filter))}
function renderCart(){const count=cart.reduce((sum,item)=>sum+item.qty,0);$('#cart-count').textContent=count;$('#cart-total').textContent=money(total());$('#cart-items').innerHTML=cart.length?cart.map(item=>{const product=getProduct(item.id);if(!product)return'';return `<div class="cart-item"><div class="cart-swatch" style="--product-color:${product.color||'#c9e66a'}">${product.photo?`<img src="${product.photo}" alt="${product.name}">`:''}</div><div><h3>${product.name}</h3><p>${product.fabric||'Moda fitness'} · ${money(product.price)}</p><div class="qty-control"><button data-action="minus" data-id="${product.id}" aria-label="Diminuir">−</button><span>${item.qty}</span><button data-action="plus" data-id="${product.id}" aria-label="Aumentar">+</button></div></div><div><b>${money(Number(product.price)*item.qty)}</b><button class="remove" data-action="remove" data-id="${product.id}">remover</button></div></div>`}).join(''):'<p class="empty-cart">Sua sacola está vazia.<br>Escolha suas peças favoritas ✦</p>'}
function openCart(){$('#cart-drawer').classList.add('open');$('#cart-backdrop').classList.add('open');$('#cart-drawer').setAttribute('aria-hidden','false')}function closeCart(){$('#cart-drawer').classList.remove('open');$('#cart-backdrop').classList.remove('open');$('#cart-drawer').setAttribute('aria-hidden','true')}
function changeQuantity(id,delta){const item=cart.find(entry=>String(entry.id)===String(id));if(!item)return;item.qty+=delta;if(item.qty<=0)cart=cart.filter(entry=>String(entry.id)!==String(id));saveCart();renderCart()}
document.addEventListener('click',event=>{const filter=event.target.closest('[data-filter]');if(filter){setFilter(filter.dataset.filter);return}const add=event.target.closest('.add');if(add){const item=cart.find(entry=>String(entry.id)===add.dataset.id);if(item)item.qty+=1;else cart.push({id:add.dataset.id,qty:1});saveCart();renderCart();openCart();return}const action=event.target.closest('[data-action]');if(action){if(action.dataset.action==='remove')cart=cart.filter(entry=>String(entry.id)!==action.dataset.id);else changeQuantity(action.dataset.id,action.dataset.action==='plus'?1:-1);saveCart();renderCart()}});$('.bag').addEventListener('click',openCart);$('.close-cart').addEventListener('click',closeCart);$('#cart-backdrop').addEventListener('click',closeCart);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeCart()});document.querySelectorAll('input[name="pay"]').forEach(input=>input.addEventListener('change',renderCart));
$('#finish-order').addEventListener('click',()=>{const name=$('#customer-name').value.trim(),phone=$('#customer-phone').value.trim();if(!cart.length||!name||!phone){alert('Adicione uma peça e informe nome e WhatsApp para finalizar.');return}const order={id:`BG-${Date.now().toString().slice(-8)}`,createdAt:new Date().toLocaleString('pt-BR'),customer:{name,phone},items:cart.map(item=>({...getProduct(item.id),qty:item.qty})),subtotal:subtotal(),total:total(),payment:$('input[name="pay"]:checked').value,status:'Aguardando pagamento'};const orders=JSON.parse(localStorage.getItem(STORAGE_ORDERS)||'[]');orders.unshift(order);localStorage.setItem(STORAGE_ORDERS,JSON.stringify(orders));const lines=order.items.map(item=>`• ${item.qty}x ${item.name} — ${money(Number(item.price)*item.qty)}`).join('\n');window.open(`https://wa.me/5561985359437?text=${encodeURIComponent(`Pedido ${order.id}\n\n${lines}\n\nTotal: ${money(order.total)}\nPagamento: ${order.payment}\nCliente: ${name}`)}`,'_blank');cart=[];saveCart();renderCart();closeCart()});$('.menu-toggle').addEventListener('click',()=>{const nav=$('.nav'),open=nav.classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String(open))});setFilter('todos');renderCart();
